/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.ResultSet;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author fuada
 */
public class akunBaru extends javax.swing.JFrame {

    /**
     * Creates new form akunBaru
     */
    void sembunyikanbtn(){
        btnsembunyikanpassword.setVisible(false);
        iconeye.setVisible(false);
        btnlihatpassword.setVisible(true);
        
    }
    public akunBaru() {
        initComponents();
        sembunyikanbtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsumbit = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        iconeye = new javax.swing.JLabel();
        btnsembunyikanpassword = new javax.swing.JPanel();
        btnlihatpassword = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsumbit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsumbit.setOpaque(false);
        btnsumbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsumbitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnsumbitLayout = new javax.swing.GroupLayout(btnsumbit);
        btnsumbit.setLayout(btnsumbitLayout);
        btnsumbitLayout.setHorizontalGroup(
            btnsumbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        btnsumbitLayout.setVerticalGroup(
            btnsumbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(btnsumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, 184, 45));

        password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(175, 0, 0));
        password.setText("***************");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 549, 270, 50));

        iconeye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye.png"))); // NOI18N
        getContentPane().add(iconeye, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 498, -1, -1));

        btnsembunyikanpassword.setBackground(new java.awt.Color(255, 255, 255));
        btnsembunyikanpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsembunyikanpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsembunyikanpasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnsembunyikanpasswordLayout = new javax.swing.GroupLayout(btnsembunyikanpassword);
        btnsembunyikanpassword.setLayout(btnsembunyikanpasswordLayout);
        btnsembunyikanpasswordLayout.setHorizontalGroup(
            btnsembunyikanpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnsembunyikanpasswordLayout.setVerticalGroup(
            btnsembunyikanpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        getContentPane().add(btnsembunyikanpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1207, 560, 40, 34));

        btnlihatpassword.setOpaque(false);
        btnlihatpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlihatpasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnlihatpasswordLayout = new javax.swing.GroupLayout(btnlihatpassword);
        btnlihatpassword.setLayout(btnlihatpasswordLayout);
        btnlihatpasswordLayout.setHorizontalGroup(
            btnlihatpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnlihatpasswordLayout.setVerticalGroup(
            btnlihatpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(btnlihatpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1207, 550, 40, 50));

        job.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 28)); // NOI18N
        job.setForeground(new java.awt.Color(175, 0, 0));
        getContentPane().add(job, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 614, 690, 120));

        username.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 110)); // NOI18N
        username.setForeground(new java.awt.Color(175, 0, 0));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 690, 120));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login/buat password.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setForeground(Color.BLUE);
        password.setText(null);
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        password.setForeground(Color.red);
        if (password.getText() == null || password.getText().isEmpty()) {

            password.setText("***************");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        password.setText(null);
    }//GEN-LAST:event_passwordMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void btnsembunyikanpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsembunyikanpasswordMouseClicked
        password.setEchoChar('*');
        sembunyikanbtn();
    }//GEN-LAST:event_btnsembunyikanpasswordMouseClicked

    private void btnlihatpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlihatpasswordMouseClicked
        password.setEchoChar((char) 0);
        btnlihatpassword.setVisible(false);
        btnsembunyikanpassword.setVisible(true);
        iconeye.setVisible(true);
    }//GEN-LAST:event_btnlihatpasswordMouseClicked

    private void btnsumbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsumbitMouseClicked
        String finaljob = job.getText();
        String usernameText = username.getText();
        usernameText = usernameText.replaceAll("!", "");
        System.out.println(finaljob);
        if (password.getText().equals("***************")) {
            password.setText(null);
        }
            try {
                String sql = "UPDATE `akun` SET `password` = '"+password.getText()+"' WHERE akun.username = ?";
                java.sql.Connection conn = (java.sql.Connection) Config.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                pst.setString(1, usernameText);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Password Berhasil Diperbarui");
                if (finaljob.equals("ADMIN")) {
                        JOptionPane.showMessageDialog(null, "Berhasil login");
                        new AdminPenjualan().setVisible(true);
                        this.dispose();
                } else if (finaljob.equals("KOKI")) {
                        JOptionPane.showMessageDialog(null, "Berhasil login");
                        new koki().setVisible(true);
                        this.dispose();
                } else if (finaljob.equals("KASIR")) {
                        JOptionPane.showMessageDialog(null, "Berhasil login");
                        new kasir().setVisible(true);
                        this.dispose();
                } else if (finaljob.equals("WAITER")) {
                        JOptionPane.showMessageDialog(null, "Berhasil login");
                        new koki().setVisible(true);
                        this.dispose();
                    }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        
        
    }//GEN-LAST:event_btnsumbitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(akunBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(akunBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(akunBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(akunBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new akunBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel btnlihatpassword;
    private javax.swing.JPanel btnsembunyikanpassword;
    private javax.swing.JPanel btnsumbit;
    private javax.swing.JLabel iconeye;
    public static final javax.swing.JLabel job = new javax.swing.JLabel();
    private javax.swing.JPasswordField password;
    public static final javax.swing.JLabel username = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
