/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class forgotpassword2 extends javax.swing.JFrame {
    public String NIK = forgotpassword1.NIK;
    /**
     * Creates new form forgotpassword2
     */
    void sembunyikanbtn(){
        btnsembunyikanpassword.setVisible(false);
        iconeye.setVisible(false);
        btnlihatpassword.setVisible(true);
        
    }
    public forgotpassword2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPasswordField();
        btnsubmit = new javax.swing.JPanel();
        iconeye = new javax.swing.JLabel();
        btnsembunyikanpassword = new javax.swing.JPanel();
        btnlihatpassword = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setEditable(false);
        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        username.setForeground(new java.awt.Color(175, 0, 0));
        username.setBorder(null);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 320, 40));

        password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(175, 0, 0));
        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 459, 280, 50));

        btnsubmit.setOpaque(false);
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsubmitMouseClicked(evt);
            }
        });
        getContentPane().add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 565, 182, 43));

        iconeye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye.png"))); // NOI18N
        getContentPane().add(iconeye, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 408, -1, -1));

        btnsembunyikanpassword.setBackground(new java.awt.Color(255, 255, 255));
        btnsembunyikanpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsembunyikanpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsembunyikanpasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnsembunyikanpasswordLayout = new javax.swing.GroupLayout(btnsembunyikanpassword);
        btnsembunyikanpassword.setLayout(btnsembunyikanpasswordLayout);
        btnsembunyikanpasswordLayout.setHorizontalGroup(
            btnsembunyikanpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnsembunyikanpasswordLayout.setVerticalGroup(
            btnsembunyikanpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        getContentPane().add(btnsembunyikanpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 470, 40, 34));

        btnlihatpassword.setOpaque(false);
        btnlihatpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlihatpasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnlihatpasswordLayout = new javax.swing.GroupLayout(btnlihatpassword);
        btnlihatpassword.setLayout(btnlihatpasswordLayout);
        btnlihatpasswordLayout.setHorizontalGroup(
            btnlihatpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnlihatpasswordLayout.setVerticalGroup(
            btnlihatpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(btnlihatpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 460, 40, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lupa Password/4.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsembunyikanpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsembunyikanpasswordMouseClicked
        password.setEchoChar('*');
        sembunyikanbtn();
    }//GEN-LAST:event_btnsembunyikanpasswordMouseClicked

    private void btnlihatpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlihatpasswordMouseClicked
        password.setEchoChar((char) 0);
        btnlihatpassword.setVisible(false);
        btnsembunyikanpassword.setVisible(true);
        iconeye.setVisible(true);
    }//GEN-LAST:event_btnlihatpasswordMouseClicked

    private void btnsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseClicked
        try{
            String sql = "UPDATE `akun` SET `password` = '"+password.getText()+"' WHERE `username` = '"+username.getText()+"';";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);

            // Menjalankan perintah update
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil...");
            this.setVisible(false);
            new MainDisplay().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Update Password");
        }
    }//GEN-LAST:event_btnsubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpassword2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel btnlihatpassword;
    private javax.swing.JPanel btnsembunyikanpassword;
    private javax.swing.JPanel btnsubmit;
    private javax.swing.JLabel iconeye;
    private javax.swing.JPasswordField password;
    public static final javax.swing.JTextField username = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
