/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fuada
 */
public class PilihTempatMakan extends javax.swing.JFrame {

    /**
     * Creates new form TempatPesanan
     */
    private String pilihTempatMakan;
    
    
    public PilihTempatMakan() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnawal = new javax.swing.JPanel();
        btncara = new javax.swing.JPanel();
        btnbawapulang = new javax.swing.JPanel();
        btnmakandisini = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnawal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnawal.setOpaque(false);
        btnawal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnawalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnawalLayout = new javax.swing.GroupLayout(btnawal);
        btnawal.setLayout(btnawalLayout);
        btnawalLayout.setHorizontalGroup(
            btnawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        btnawalLayout.setVerticalGroup(
            btnawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(btnawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, -1, 60));

        btncara.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncara.setOpaque(false);

        javax.swing.GroupLayout btncaraLayout = new javax.swing.GroupLayout(btncara);
        btncara.setLayout(btncaraLayout);
        btncaraLayout.setHorizontalGroup(
            btncaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        btncaraLayout.setVerticalGroup(
            btncaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(btncara, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 670, -1, 60));

        btnbawapulang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbawapulang.setOpaque(false);
        btnbawapulang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbawapulangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnbawapulangLayout = new javax.swing.GroupLayout(btnbawapulang);
        btnbawapulang.setLayout(btnbawapulangLayout);
        btnbawapulangLayout.setHorizontalGroup(
            btnbawapulangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        btnbawapulangLayout.setVerticalGroup(
            btnbawapulangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(btnbawapulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 420, 410));

        btnmakandisini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmakandisini.setOpaque(false);
        btnmakandisini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmakandisiniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnmakandisiniLayout = new javax.swing.GroupLayout(btnmakandisini);
        btnmakandisini.setLayout(btnmakandisiniLayout);
        btnmakandisiniLayout.setHorizontalGroup(
            btnmakandisiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        btnmakandisiniLayout.setVerticalGroup(
            btnmakandisiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(btnmakandisini, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 420, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnawalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnawalMouseClicked
        new PembeliDisplay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnawalMouseClicked

    private void btnmakandisiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmakandisiniMouseClicked
        try {
            MainPesanPembeli.finalPilihTempatMakan.setText("Makan Di Sini");
            new MainPesanPembeli().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(PilihTempatMakan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmakandisiniMouseClicked

    private void btnbawapulangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbawapulangMouseClicked
        try {
            MainPesanPembeli.finalPilihTempatMakan.setText("Bawa Pulang");
            new MainPesanPembeli().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(PilihTempatMakan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbawapulangMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihTempatMakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihTempatMakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihTempatMakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihTempatMakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnawal;
    private javax.swing.JPanel btnbawapulang;
    private javax.swing.JPanel btncara;
    private javax.swing.JPanel btnmakandisini;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
